name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/github-snake.svg

      - name: Push generated snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          path: dist/github-snake.svg
